name: projet2
description: "A new Flutter project."
publish_to: 'none'  # Si tu ne veux pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.4
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.2
  shared_preferences: ^2.3.3
  share_plus: ^10.1.2
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^18.0.1

  timezone: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"

flutter_native_splash:
  color: "#42a5f5"
  image: assets/img/logo.png
  android: true
  ios: true


flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
